import { InventoryItem } from '@/lib/types'

/**
 * Catalogo de material quirurgico de alto valor.
 *
 * consumptionRate = unidades consumidas por dia (media).
 * leadTimeDays    = plazo de entrega del proveedor en dias.
 */
export type CatalogItem = Omit<
  InventoryItem,
  'id' | 'quantity' | 'status' | 'aiPredictedDemand' | 'location'
>

export const SURGICAL_CATALOG: CatalogItem[] = [
  // Neurocirugia
  {
    name: 'StealthStation S8 - Kit de navegacion craneal',
    manufacturer: 'Medtronic',
    sku: 'MDT-STL-CRN',
    category: 'Navegacion quirurgica',
    department: 'neurosurgery',
    minStock: 6,
    maxStock: 20,
    unit: 'kits',
    price: 1850,
    expirationDate: '2027-09-30',
    supplier: 'Medtronic Iberica',
    consumptionRate: 0.45,
    leadTimeDays: 14,
  },
  {
    name: 'Midas Rex MR8 - Fresa de craneotomia',
    manufacturer: 'Medtronic',
    sku: 'MDT-MR8-CRN',
    category: 'Motores y fresas',
    department: 'neurosurgery',
    minStock: 10,
    maxStock: 40,
    unit: 'fresas',
    price: 420,
    expirationDate: '2028-03-31',
    supplier: 'Medtronic Iberica',
    consumptionRate: 0.9,
    leadTimeDays: 10,
  },
  {
    name: 'Certas Plus - Valvula de derivacion programable',
    manufacturer: 'Integra LifeSciences',
    sku: 'INT-CRT-PLS',
    category: 'Implantes neuroquirurgicos',
    department: 'neurosurgery',
    minStock: 4,
    maxStock: 12,
    unit: 'valvulas',
    price: 3200,
    expirationDate: '2028-06-30',
    supplier: 'Integra Espana',
    consumptionRate: 0.15,
    leadTimeDays: 21,
  },
  // Cirugia robotica
  {
    name: 'da Vinci Xi - EndoWrist Large Needle Driver',
    manufacturer: 'Intuitive Surgical',
    sku: 'IS-470006',
    category: 'Cirugia robotica',
    department: 'surgery',
    minStock: 8,
    maxStock: 24,
    unit: 'instrumentos',
    price: 2900,
    expirationDate: '2029-01-31',
    supplier: 'Abex Excelencia Robotica',
    consumptionRate: 0.6,
    leadTimeDays: 15,
  },
  {
    name: 'da Vinci Xi - Maryland Bipolar Forceps',
    manufacturer: 'Intuitive Surgical',
    sku: 'IS-470172',
    category: 'Cirugia robotica',
    department: 'surgery',
    minStock: 8,
    maxStock: 24,
    unit: 'instrumentos',
    price: 3100,
    expirationDate: '2029-01-31',
    supplier: 'Abex Excelencia Robotica',
    consumptionRate: 0.55,
    leadTimeDays: 15,
  },
  {
    name: 'da Vinci Xi - Recarga SureForm 60',
    manufacturer: 'Intuitive Surgical',
    sku: 'IS-SF60-RLD',
    category: 'Cirugia robotica',
    department: 'surgery',
    minStock: 20,
    maxStock: 80,
    unit: 'recargas',
    price: 610,
    expirationDate: '2027-11-30',
    supplier: 'Abex Excelencia Robotica',
    consumptionRate: 2.4,
    leadTimeDays: 12,
  },
  {
    name: 'da Vinci Xi - Funda esteril de brazo',
    manufacturer: 'Intuitive Surgical',
    sku: 'IS-470015',
    category: 'Cirugia robotica',
    department: 'surgery',
    minStock: 40,
    maxStock: 160,
    unit: 'fundas',
    price: 145,
    expirationDate: '2027-08-31',
    supplier: 'Abex Excelencia Robotica',
    consumptionRate: 4.5,
    leadTimeDays: 10,
  },
  {
    name: 'Harmonic ACE+7 - Bisturi ultrasonico',
    manufacturer: 'Ethicon (J&J MedTech)',
    sku: 'ETH-HARH36',
    category: 'Energia quirurgica',
    department: 'surgery',
    minStock: 15,
    maxStock: 50,
    unit: 'unidades',
    price: 780,
    expirationDate: '2027-12-31',
    supplier: 'Johnson & Johnson MedTech',
    consumptionRate: 1.6,
    leadTimeDays: 7,
  },
  // Cardiologia intervencionista
  {
    name: 'Resolute Onyx - Stent coronario farmacoactivo',
    manufacturer: 'Medtronic',
    sku: 'MDT-RONYX-30',
    category: 'Hemodinamica',
    department: 'cardiology',
    minStock: 30,
    maxStock: 100,
    unit: 'stents',
    price: 690,
    expirationDate: '2027-05-31',
    supplier: 'Medtronic Iberica',
    consumptionRate: 3.2,
    leadTimeDays: 7,
  },
  {
    name: 'SAPIEN 3 Ultra RESILIA - Valvula aortica TAVI',
    manufacturer: 'Edwards Lifesciences',
    sku: 'EW-S3UR-26',
    category: 'Valvulas transcateter',
    department: 'cardiology',
    minStock: 3,
    maxStock: 10,
    unit: 'valvulas',
    price: 19500,
    expirationDate: '2027-10-31',
    supplier: 'Edwards Lifesciences Spain',
    consumptionRate: 0.2,
    leadTimeDays: 20,
  },
  {
    name: 'Micra AV2 - Marcapasos sin cables',
    manufacturer: 'Medtronic',
    sku: 'MDT-MC2AV',
    category: 'Estimulacion cardiaca',
    department: 'cardiology',
    minStock: 4,
    maxStock: 12,
    unit: 'dispositivos',
    price: 9800,
    expirationDate: '2028-02-28',
    supplier: 'Medtronic Iberica',
    consumptionRate: 0.25,
    leadTimeDays: 14,
  },
  {
    name: 'MitraClip G4 - Sistema de reparacion mitral',
    manufacturer: 'Abbott',
    sku: 'ABT-MCG4-XTW',
    category: 'Valvulas transcateter',
    department: 'cardiology',
    minStock: 2,
    maxStock: 6,
    unit: 'sistemas',
    price: 24000,
    expirationDate: '2027-07-31',
    supplier: 'Abbott Medical Espana',
    consumptionRate: 0.08,
    leadTimeDays: 25,
  },
  // Traumatologia y columna
  {
    name: 'Mako - Kit desechable artroplastia de rodilla',
    manufacturer: 'Stryker',
    sku: 'SYK-MAKO-TKA',
    category: 'Cirugia robotica',
    department: 'traumatology',
    minStock: 6,
    maxStock: 20,
    unit: 'kits',
    price: 1350,
    expirationDate: '2027-09-30',
    supplier: 'Stryker Iberia',
    consumptionRate: 0.7,
    leadTimeDays: 12,
  },
  {
    name: 'Persona - Protesis total de rodilla',
    manufacturer: 'Zimmer Biomet',
    sku: 'ZB-PERS-CR',
    category: 'Implantes ortopedicos',
    department: 'traumatology',
    minStock: 10,
    maxStock: 30,
    unit: 'implantes',
    price: 2600,
    expirationDate: '2030-12-31',
    supplier: 'Zimmer Biomet Spain',
    consumptionRate: 0.8,
    leadTimeDays: 10,
  },
  {
    name: 'Expedium 5.5 - Tornillo pedicular poliaxial',
    manufacturer: 'DePuy Synthes',
    sku: 'DPS-EXP55-PA',
    category: 'Implantes de columna',
    department: 'traumatology',
    minStock: 40,
    maxStock: 140,
    unit: 'tornillos',
    price: 310,
    expirationDate: '2031-06-30',
    supplier: 'Johnson & Johnson MedTech',
    consumptionRate: 3.5,
    leadTimeDays: 9,
  },
]
